# Generated by Django 2.0.2 on 2018-02-11 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favourite_books_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_books',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
