# Generated by Django 2.0.2 on 2018-02-15 23:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0001_initial'),
        ('users', '0002_favourite_books_favouritecategory_newsletter_ratebook_readbook'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together={('user', 'author')},
        ),
        migrations.AlterModelTable(
            name='newsletter',
            table='newsletter',
        ),
    ]
