# Generated by Django 2.0.2 on 2018-02-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180211_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite_books',
            name='date',
        ),
    ]
