# Generated by Django 2.0.2 on 2018-02-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180215_2304'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='readbook',
            table='ReadBook',
        ),
    ]
