# Generated by Django 2.0.2 on 2018-02-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_favourite_books_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite_books',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
