# Generated by Django 2.0.2 on 2018-02-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_favourite_books_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite_books',
            name='date',
        ),
    ]
