# Generated by Django 2.0.2 on 2018-02-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180210_0859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
